### PR TITLE
(Re)install and Uninstall Failsafe Script

### PR DESCRIPTION
**Pull request by ipitio**
This is part of https://github.com/arevindh/AdminLTE/pull/70

Features:
* New `mod.sh` script
  * Unified script
  * Provides failsafe capability
  * Revert to upstream without updating (even without a backup (git checkout))
  * Adds speedtest repo
  * Only installs speedtest if no repo

Fixes:
* Backup all modified files
  * Makes uninstall faster
* Backups use predictable names
  * No more old backups taking up space

### CODE REVIEW

**Comment by ipitio** [comment]
Everything works now!

**Comment by town3r** [comment]
I got this error when running your install/upgrde script

```
fatal: HEAD does not point to a branch
Error: Remote revision could not be obtained, please contact Pi-hole Support Additional debugging output:
HEAD detached at v5.18.1
```

image

**Comment by ipitio** [comment]
@town3r oops forgot to sync test branch, should work now

**Comment by town3r** [comment]
Still getting some errors:

image

**Comment by ipitio** [comment]
Hmm now I'm only cloning the last commit, could you try now

**Comment by town3r** [comment]
No dice.

image

image

**Comment by ipitio** [comment]
what about now

**Comment by town3r** [comment]
Still getting the HEAD detached error. :( 

No more crazy long list of version tags.

image

**Comment by ipitio** [comment]
what about now

**Comment by town3r** [comment]
This is what I'm getting currently:

image

**Comment by ipitio** [comment]
Woo! It works! I'll get rid of those errors but they don't matter.

**Comment by town3r** [comment]
image

**Comment by ipitio** [comment]
Lol no way they released an update rn. Perfect timing to test how my script would handle a pihole update before the mod is updated for it. And looks like the test passed so that's good

**Comment by ipitio** [comment]
How have you been running speedtests without speedtest?

**Comment by town3r** [comment]
I have speedtest, so not sure why it said it couldn't find it.

image

**Comment by ipitio** [comment]
How did you install it? What instructions did you use to install it or who's script did you use?

**Comment by town3r** [comment]
Used the install steps from arevindh

https://github.com/arevindh/pihole-speedtest/wiki/Installing-Speedtest-Mod#install-speedtest-cli

Grabbed link to latest version here

https://www.speedtest.net/apps/cli

ie: https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-armhf.tgz

**Comment by ipitio** [comment]
Ah, will now account for that

**Comment by ipitio** [comment]
Can u take a sc of the output now

**Comment by town3r** [comment]
image

**Comment by town3r** [comment]
Ahh your new script added a bad repo

image

**Comment by ipitio** [comment]
Yeah ookla is dumb and don't detect os properly, I'm fixing their script

**Comment by town3r** [comment]
Is your script trying to reinstall the speedtest app itself and the speedtest pihole mod?

**Comment by ipitio** [comment]
It's trying to add the speedtest source so that apt knows what speedtest is and stops showing that error. Otherwise the script does exactly what those time stamps say it's doing.

**Comment by ipitio** [comment]
Try now

**Comment by town3r** [comment]
image

**Comment by town3r** [comment]
Doesn't look like it's auto running the Speedtest hourly like within the settings tho. :( 

image

**Comment by ipitio** [comment]
Could you click confirm in speedtest settings? Just confirm. Should work after, we'll know in 30 min. Simply updating doesn't update/fix the timer cuz sid wanted that to only happen when user selects confirm.

**Comment by ipitio** [comment]
And then you could send a sc of that cat command

**Comment by town3r** [comment]
Cat command?

**Comment by ipitio** [comment]
`cat /var/log/pimod.log` it's at the bottom of speedtest settings

**Comment by town3r** [comment]
image

**Comment by ipitio** [comment]
Did the Speedtest run

**Comment by town3r** [comment]
Looks like it! 🥳
image

**Comment by town3r** [comment]
Hmm I'm now seeing this when manually running `pihole -up`

image

**Comment by ipitio** [comment]
I think the local revision thing is because my latest changes aren't under a release.

Are the DNS issues related to the Mod?

Did running pihole -up work before, even with the mod still installed? If so it might be unnecessary to uninstall the mod before updating pihole.

**Comment by town3r** [comment]
> I think the local revision thing is because my latest changes aren't under a release, if pihole -up worked before.
> Are the DNS issues related to the Mod?
I think so? Only thing that I've changed has been from your script.

> Did running pihole -up work before, even with the mod still installed? If so it might be unnecessary to uninstall the mod before updating pihole. 

It did work before. I'll try uninstalling the mod via the settings option, running pihole -up followed by running your script again

**Comment by town3r** [comment]
Didn't even have to uninstall, actually just ran arevindh's upgrade script and once ran I was able to run pihole -up successfully.

Running your script, brought back the errors from above

**Comment by ipitio** [comment]
Just added a new tag, if pihole -up works now then it means it'll work when sid merges. It just won't work when updating to my test branch. If it still doesn't work, then ig just don't use it when you have the mod installed lol. Is it vital that it works?

**Comment by town3r** [comment]
Any idea why the hourly tests would stop randomly at 11 yesterday?

image

**Comment by arevindh** [comment]
That's weird

**Comment by town3r** [comment]
Looks like it started back up at 08:00 this morning due to me selecting the `(Re)install Latest` option under Speedtest Settings at like 07:30.

image

So something must have been off w/ the previous version ¯\_(ツ)_/¯

**Comment by town3r** [comment]
> That's weird 

Right! Not sure what happened/changed around that time.

¯\_(ツ)_/¯ 

Glad it seems to be happy again since running your fancy `(Re)install Latest` feature.

**Pull request merged**
